---
abstract: 'Determines if a module is Dual-Lived'
author:
  - 'Kevin W. Henwood <Khen1950fx@aol.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App-DualLivedList
name: App-DualLivedList
no_index:
  directory:
    - inc
    - t
requires:
  CPAN: Memoize
  Module::CoreList: Term::ANSIColor::Print
  Test::Kwalitee: 0
  Test::More: Test::Script
  Test::Pod: Test::Pod::Coverage
version: 0.00_05
